apiVersion: v1
kind: Service
metadata:
  labels:
    app: nodejsapp
  name: nodejsapp-service
spec:
  selector:
    app: nodejsapp
  type: NodePort
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  type: NodePort