apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nodejsapp
  name: nodejsapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejsapp
  template:
    metadata:
      labels:
        app: nodejsapp
    spec:
      containers:
      - image: ${DOCKER_IMAGE_TAG}
        name: nodejsapp
        ports:
        - containerPort: 3000